add: Night Of The Dead
pelican-eggs/games-steamcmd pull request #37
Opened 2024-06-12 09:38 UTC by QuintenQVD0

# Description

closes #36 

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

## New egg Submissions

1. [ ] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [ ] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [ ] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [x] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [x] The egg was exported from the panel

2024-06-12 14:35 UTC, scootz commented
I tested the new egg, did it twice to make sure.  I get a 404 error where it tries to curl the gamesettings.ini and this is the resulting file below. I've deleted the obvious settings but other than that I left it as it was. 

![image](https://github.com/pelican-eggs/games-steamcmd/assets/574344/05644f34-0b6e-47cd-adaf-f48bca3ba4c6)

2024-06-12 14:55 UTC, gOOvER requested changes

2024-06-12 14:55 UTC, gOOvER commented on night_of_the_dead/egg-pterodactyl-night-of-the-dead.json
> +            "default_value": "vcrun2019 corefonts",
use vcrun2022. it cointains all other versions

2024-06-12 14:55 UTC, gOOvER commented
> I tested the new egg, did it twice to make sure. I get a 404 error where it tries to curl the serversettings.ini and this is the resulting file below. I've deleted the obvious settings but other than that I left it as it was.
> 
> ![image](https://private-user-images.githubusercontent.com/574344/339012997-05644f34-0b6e-47cd-adaf-f48bca3ba4c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDQ0MjgsIm5iZiI6MTcxODIwNDEyOCwicGF0aCI6Ii81NzQzNDQvMzM5MDEyOTk3LTA1NjQ0ZjM0LTBiNmUtNDdjZC1hZGFmLWY0OGJjYTNiYTRjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQxNDU1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjY3MTM2OTZkODZiOTlmNzBhYmRlYmUwNzg4NjNjNTVmODYzZTVlNDZjNjBmYWU0YjM1ODQ4NDk5NzQ5ZjNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PHLs4WfOYBRx3T0EuGY4OFYLkOyWwILskDfQ3_sKvV0)

yes, because its not in the repo yet

2024-06-12 16:27 UTC, QuintenQVD0 commented
> I tested the new egg, did it twice to make sure. I get a 404 error where it tries to curl the serversettings.ini and this is the resulting file below. I've deleted the obvious settings but other than that I left it as it was.
> 
> ![image](https://private-user-images.githubusercontent.com/574344/339012997-05644f34-0b6e-47cd-adaf-f48bca3ba4c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDk5MTEsIm5iZiI6MTcxODIwOTYxMSwicGF0aCI6Ii81NzQzNDQvMzM5MDEyOTk3LTA1NjQ0ZjM0LTBiNmUtNDdjZC1hZGFmLWY0OGJjYTNiYTRjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQxNjI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWRhYTVkNGFjNzg4YzUxYThlZWRiZjIzMWRhYjkzOWQwMzY2ZmJiMTNhZDQ3NTBkMGYxYTI0ZDJkZTQyMDY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m86cs-QKfzEE8xrGICbwvlcsAtWK3Whi7WODWEetm8w)

Yes that is because the file will only exits after the egg has been merged, thats normal

2024-06-12 19:16 UTC, scootz commented on night_of_the_dead/egg-pterodactyl-night-of-the-dead.json
> +            "env_variable": "ENABLE_PVP",
ENABLE_PVP should be changed to PVP to match what is in the configuration files section.

2024-06-13 12:26 UTC, scootz commented on night_of_the_dead/egg-pterodactyl-night-of-the-dead.json
> +            "env_variable": "SAVEGAME_NAME",
This SAVEGAME_NAME does not match what is in the configuration files section which has SERVER_SAVEGAME.

2024-06-14 20:49 UTC, scootz commented on night_of_the_dead/README.md
> +# Nigh of the dead
Typo,  Night.
```suggestion
# Night of the dead

```

2024-06-14 20:51 UTC, scootz commented on night_of_the_dead/ServerSettings.ini
> +SaveName=/home/container/Saved/SaveGames/
```suggestion
SaveName=/home/container/LF/Saved/SaveGames/

```

2024-06-14 20:54 UTC, scootz commented on night_of_the_dead/egg-night-of-the-dead.json
> +        "files": "{\n    \".\/LF\/Saved\/Config\/ServerSettings.ini\": {\n        \"parser\": \"ini\",\n        \"find\": {\n            \"ServerSettings.ServerName\": \"{{server.environment.SERVER_N
SystemSettings.SaveName should have a path change  including the 'LF' directory in the path. /home/container/LF/Saved/SaveGames/{{server.environment.SERVER_SAVEGAME}}

2024-06-14 20:56 UTC, scootz commented on night_of_the_dead/egg-night-of-the-dead.json
> +            "script": "#!\/bin\/bash\r\n# steamcmd Base Installation Script\r\n#\r\n# Server Files: \/mnt\/server\r\n# Image to install with is 'ghcr.io\/parkervcp\/installers:debian'\r\n\r\n# Instal
Where it makes the savegames path, should include 'LF' directory.   mkdir -p /mnt/server/LF/SaveGames

2024-06-14 20:58 UTC, scootz commented on night_of_the_dead/egg-night-of-the-dead.json
> +            "env_variable": "ENABLE_PVP",
This should be changed to 'PVP' to match configuration files section variable usage.

2024-06-14 21:05 UTC, scootz commented on night_of_the_dead/egg-night-of-the-dead.json
> +            "env_variable": "SAVEGAME_NAME",
make this match configuration files section variable usage.
```suggestion
            "env_variable": "SERVER_SAVEGAME",
```

2024-06-14 21:07 UTC, scootz commented on night_of_the_dead/egg-pterodactyl-night-of-the-dead.json
> +        "files": "{\n    \".\/LF\/Saved\/Config\/ServerSettings.ini\": {\n        \"parser\": \"ini\",\n        \"find\": {\n            \"ServerSettings.ServerName\": \"{{env.SERVER_NAME}}\",\n
```suggestion
        "files": "{\n    \".\/LF\/Saved\/Config\/ServerSettings.ini\": {\n        \"parser\": \"ini\",\n        \"find\": {\n            \"ServerSettings.ServerName\": \"{{env.SERVER_NAME}}\",\n            \"ServerSettings.Password\": \"{{env.SERVER_PASSWORD}}\",\n            \"SystemSettings.SaveName\": \"\/home\/container\/LF\/Saved\/SaveGames\/{{env.SERVER_SAVEGAME}}\",\n            \"SystemSettings.IngameAdminPassword\": \"{{env.SERVER_ADMIN_PASSWORD}}\",\n            \"SystemSettings.DefaultMessageOfTheDay\": \"{{env.SERVER_MOTD}}\",\n            \"GameSettings.Difficulty\": \"{{env.DIFFICULTY}}\",\n            \"GameSettings\/General.MODSelect\": \"{{env.PVP}}\"\n        }\n    }\n}",
```

2024-06-14 21:12 UTC, scootz commented on night_of_the_dead/egg-pterodactyl-night-of-the-dead.json
> +            "script": "#!\/bin\/bash\r\n# steamcmd Base Installation Script\r\n#\r\n# Server Files: \/mnt\/server\r\n# Image to install with is 'ghcr.io\/parkervcp\/installers:debian'\r\n\r\n# Instal
Again, in here, change where it makes the savegame directory to include /LF/ in the path.    mkdir -p \/mnt\/server\/LF\/Saved\/SaveGames

2024-06-14 21:44 UTC, scootz commented
There is also this that happens with repeated paths i'm not sure how to fix this.
![image](https://github.com/pelican-eggs/games-steamcmd/assets/574344/b3c1ff49-a06e-41dd-ae45-f99a446f5964)

2024-06-15 07:47 UTC, QuintenQVD0 commented
@scootz I made the request changes and I also made the console output work, please re-test with a new server (not updating an existing one) the savegame path should be fixt

2024-06-15 11:39 UTC, scootz commented
Works good.  There is still the issue with the saved game path.
![image](https://github.com/pelican-eggs/games-steamcmd/assets/574344/40f04d54-d2da-4612-9da1-8f25758305d8)

2024-06-15 11:53 UTC, QuintenQVD0 commented
> Works good. There is still the issue with the saved game path. The panel still thinks its crashing when stopping the server.
> 
> ![image](https://private-user-images.githubusercontent.com/574344/339982369-40f04d54-d2da-4612-9da1-8f25758305d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NTI1ODMsIm5iZiI6MTcxODQ1MjI4MywicGF0aCI6Ii81NzQzNDQvMzM5OTgyMzY5LTQwZjA0ZDU0LWQyZGEtNDYxMi05ZGExLThmMjU3NTgzMDVkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQxMTUxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTRmZTg5ZTg2ZTQ3OTNhYmFlMjJjYjY2YzFiOTM2ZDc1Nzc0NjlkMzllMmQxZjVlNWVkZDYwNDdjNjhlMzA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o040oAmjzCA7GEZifzPOGGiN1hgfsCZqiFP1fkc3VIA)

that thinking that is crashed is something I also have (on pelican no idea if you are on that or ptero).

the savegames I did not have one as I do not own the game so I could not join ofc.

2024-06-15 11:59 UTC, scootz commented
The game works, its just confusing when anyone would want to restore a saved game.  Might I suggest changing in the configuration files section the ServerSettings.SaveName to omit the /home/container/LF/Saved/SaveGames/  and just have the variable {{server.environment.SERVER_SAVEGAME}}

This is running on pelican.

2024-06-15 12:05 UTC, QuintenQVD0 commented
> The game works, its just confusing when anyone would want to restore a saved game. Might I suggest changing in the configuration files section the ServerSettings.SaveName to omit the /home/container/LF/Saved/SaveGames/ and just have the variable {{server.environment.SERVER_SAVEGAME}}
> 
> This is running on pelican.

you can try that if you want, It sees like you know where to find it.

2024-06-15 12:26 UTC, scootz commented
Ok yea just having the variable works.  So the only thing left I think is pelican thinking its crashed when stopping the server.

2024-06-15 12:40 UTC, QuintenQVD0 commented
> Ok yea just having the variable works. So the only thing left I think is pelican thinking its crashed when stopping the server.

that's an issue at panel level not egg as I read that more than 1 egg have this.

2024-06-15 17:02 UTC, QuintenQVD0 commented
> Ok yea just having the variable works. So the only thing left I think is pelican thinking its crashed when stopping the server.

Change made, should be good to go now!

2024-06-15 17:28 UTC, gOOvER commented
a long discussion for a really simple egg :D I have an egg since release. Its really easy to create

2024-06-15 17:33 UTC, gOOvER commented
the savegame fix was not needed. Users are able to rename it before uploading it. An egg is only for 1 server and not for a lot of savegames ;)

2024-06-15 17:39 UTC, QuintenQVD0 commented
> able to rename it before u

it had a double path in it because savegame name was set to a path not a filename and auto prefixt by the parser.
It is fine this way now.

2024-06-15 19:02 UTC, scootz approved these changes
Everything so far looks good to me and works fine in the panel.  Game works as expected. Ty!

2024-06-16 15:59 UTC, WSG-ViViV commented
Hello All, I have tried this egg. Need it something special ?? I have this error :
[2024.06.16-15.56.10:655][604]LogStreaming: Error: Found 1 dependent packages...
[2024.06.16-15.56.10:666][604]LogStreaming: Error:   /Game/maps/LFMap/LFMap_Land_140
And noway to start it. 
Everything is up to date and it's not my first install ^^

2024-06-16 16:00 UTC, gOOvER commented
> Hello All, I have tried this egg. Need it something special ?? I have this error : [2024.06.16-15.56.10:655][604]LogStreaming: Error: Found 1 dependent packages... [2024.06.16-15.56.10:666][604]LogStreaming: Error: /Game/maps/LFMap/LFMap_Land_140 And noway to start it. Everything is up to date... Let me know if I can do something for help

this error is normally on a "notice"

2024-06-16 16:13 UTC, WSG-ViViV commented
It's the last line in logs before crash.
[LF.log](https://github.com/user-attachments/files/15858972/LF.log)

2024-06-16 16:16 UTC, gOOvER commented
problem with your home network

`LogStreaming: Warning: Failed to read file 'Z:/home/container/Cloud/IoStoreOnDemand.ini' error.`

2024-06-16 16:22 UTC, WSG-ViViV commented
Ook, that don't help me --' 
I will try to know why it don't work with me.
I have another server on same node and it work well...

2024-06-16 16:24 UTC, gOOvER commented
> Ook, that don't help me --' I will try to know why it don't work with me. I have another server on same node and it work well...

could be a failed installation

2024-06-16 16:45 UTC, WSG-ViViV commented
Ook i have try on another node and it work well
Thank's for help =))

2024-07-17 10:15 UTC, merged